// src/features/ContactForm/index.tsx
import { useContactMe } from "hooks";
import { TextInput } from "components";
import cx from "classnames";
import { MdSend } from "react-icons/md";
import { AiOutlineLoading } from "react-icons/ai";
import { FormEventHandler, HTMLAttributes } from "react";

interface Props extends HTMLAttributes<HTMLFormElement> {
  formprops: ReturnType<typeof useContactMe>;
}

export function ContactForm(props: Props) {
  const {
    name,
    onName,
    email,
    onEmail,
    subject,
    onSubject,
    message,
    onMessage,
    handleSubmit,
    isLoading,
  } = props.formprops;

  return (
    <form {...props} onSubmit={handleSubmit}>
      <div className="flex flex-col md:flex-row md:gap-3">
        <TextInput
          id="name"
          type="text"
          label="Name"
          value={name}
          onChange={onName}
          required
        />
        <TextInput
          id="email"
          type="email"
          label="Email"
          value={email}
          onChange={onEmail}
          required
        />
      </div>
      <TextInput
        id="subject"
        label="Subject"
        value={subject}
        onChange={onSubject}
        required
      />

      <div className="relative group mt-6">
        <label
          htmlFor="message"
          className={cx([
            "absolute top-0 -translate-y-1/2",
            "bg-slate-900 scale-75 px-3 text-brand-100/25",
            "group-focus-within:text-brand-50",
            "transition-smooth",
          ])}
        >
          Message
        </label>
        <textarea
          id="message"
          className={cx([
            "peer w-full text-gray-50 outline-none",
            "bg-transparent p-3 min-h-[8rem]",
            "border border-brand-300 rounded-lg",
            "placeholder:text-brand-100/25",
          ])}
          placeholder="This project is awesome..."
          value={message}
          onInput={onMessage as FormEventHandler<HTMLTextAreaElement>}
          required
        />
      </div>

      <button
        className="btn btn-primary flex items-center gap-2 mx-auto mt-6"
        type="submit"
      >
        Send
        {isLoading ? <AiOutlineLoading className="animate-spin" /> : <MdSend />}
      </button>
    </form>
  );
}

// src/components/ContactForm.svelte
<script lang="ts">
    let email: string;
    let message: string;
    let name: string;
</script>

<div class="w-full">
    <form action="" class="flex flex-col items-center gap-3 max-w-md mx-auto">
        <input placeholder="Name" type="text" required bind:value={name} />
        <input placeholder="Email" type="email" required bind:value={email} />
        <textarea placeholder="Message" required bind:value={message} />

        <button
            type="submit"
            class="bg-accent-200 text-slate-950 w-max px-3 py-2 rounded-md font-bold hover:bg-accent-100 transition-all"
            >Send</button
        >
    </form>
</div>

<style lang="postcss">
    input,
    textarea {
        @apply bg-slate-950 border border-slate-900;
        @apply min-h-[3em] rounded-md p-3 w-full;
        @apply placeholder:text-slate-700 placeholder:text-sm;
    }

    textarea {
        @apply min-h-[5em];
    }
</style>
