// src/components/Footer/ContactForm.tsx
import { useContactMe } from "hooks";
import { TextInput } from "./TextInput";
import cx from "classnames";
import { MdSend } from "react-icons/md";

export function ContactForm() {
  const { name, onName, email, onEmail, subject, onSubject } = useContactMe();

  return (
    <form>
      <TextInput id="name" label="Name" value={name} onChange={onName} />
      <TextInput id="email" label="Email" value={email} onChange={onEmail} />
      <TextInput
        id="subject"
        label="Subject"
        value={subject}
        onChange={onSubject}
      />

      <div
        className={cx([
          "text-gray-600 focus-within:text-brand-50 transition-all duration-200",
          "flex flex-col items-start",
        ])}
      >
        <label htmlFor="message" className="group-focus:text-brand-50">
          Message
        </label>
        <textarea
          id="message"
          className={cx([
            "group w-full text-gray-50",
            "bg-transparent",
            "border border-brand-50/50 rounded-sm",
          ])}
        />
      </div>

      <button className="btn btn-primary flex items-center gap-3">
        Send <MdSend />
      </button>
    </form>
  );
}

// src/components/ContactForm.svelte
<script lang="ts">
    let email: string;
    let message: string;
    let name: string;
</script>

<div class="w-full">
    <form action="" class="flex flex-col items-center gap-3 max-w-md mx-auto">
        <input placeholder="Name" type="text" required bind:value={name} />
        <input placeholder="Email" type="email" required bind:value={email} />
        <textarea placeholder="Message" required bind:value={message} />

        <button
            type="submit"
            class="bg-accent-200 text-slate-950 w-max px-3 py-2 rounded-md font-bold hover:bg-accent-100 transition-all"
            >Send</button
        >
    </form>
</div>

<style lang="postcss">
    input,
    textarea {
        @apply bg-slate-950 border border-slate-900;
        @apply min-h-[3em] rounded-md p-3 w-full;
        @apply placeholder:text-slate-700 placeholder:text-sm;
    }

    textarea {
        @apply min-h-[5em];
    }
</style>
